const type = {}
	type.GET_USER_INFO = 'GET_USER_INFO'
	type.UPDATE_USER_NICKNAME = 'UPDATE_USER_NICKNAME'
	type.UPDATE_USER_SIGNATURE = 'UPDATE_USER_SIGNATURE'

	type.FRIEND_LIST = 'FRIEND_LIST'
	type.GET_FRIEND_INFO = 'GET_FRIEND_INFO'
	type.ADD_FRIEND = 'ADD_FRIEND'
	type.DELETE_FRIEND = 'DELETE_FRIEND'
    type.UPDATE_FRIEND_INFO = 'UPDATE_FRIEND_NFO'
	
	type.GET_NEW_FRIEND_LIST = 'GET_NEW_FRIEND_LIST'
	type.ADD_NEW_FRIEND_LIST = 'ADD_NEW_FRIEND_LIST'
	type.UNREAD_FRIEND_REQUEST = 'UNREAD_FRIEND_REQUEST'
	type.DELETE_ONE_FRIEND_REQUEST = 'DELETE_ONE_FRIEND_REQUEST'
	
	type.ADD_NEW_FRIEND_MSG = 'ADD_NEW_FRIEND_MSG'

	type.GROUP_LIST = 'GROUP_LIST'
	type.GET_GROUP_INFO = 'GET_GROUP_INFO'
	type.ADD_GROUP = 'ADD_GROUP'
	type.DELETE_GROUP = 'DELETE_GROUP'
	type.UPDATE_GROUP_INFO = 'UPDATE_GROUP_NAME'
	type.GET_GROUP_NOTICE = 'GET_GROUP_NOTICE'

	type.LOCAL_SEARCH_RESULT = 'LOCAL_SEARCH_RESULT'
	type.CLEAR_LOCAL_SEARCH_RESULT = 'CLEAR_LOCAL_SEARCH_RESULT'
	type.SEARCH_CONTENT = 'SEARCH_CONTENT'

	type.CONVERSATION_LIST = 'CONVERSATION_LIST'
	type.UPDATE_CONVERSATION_SENTTIME = 'UPDATE_CONVERSATION_SENTTIME'
	type.UPDATE_CONVERSATION_LATESTMSG = 'UPDATE_CONVERSATION_MESSAGE_LATESTMSG'
	type.UPDATE_CONVERSATION_SENDERNAME = 'UPDATE_CONVERSATION_MESSAGE_SENDERNAME'
	type.UPDATE_CONVERSATION_UNREADCOUNT = 'UPDATE_CONVERSATION_UNREADCOUNT'
	type.UPDATE_CONVERSATION_NICKNAME = 'UPDATE_CONVERSATION_NICKNAME'
	type.UPDATE_CONVERSATION_ICON = 'UPDATE_CONVERSATION_ICON'
	type.UPDATE_CONVERSATION_ISTOP = 'UPDATE_CONVERSATION_ISTOP'
	type.UPDATE_CONVERSATION_NOTIPS = 'UPDATE_CONVERSATION_NOTIPS'
	type.UPDATE_CONVERSATION_LAST_READTIME = 'UPDATE_CONVERSATION_LAST_READTIME'
	type.ADD_ONE_CONVERSATION = 'ADD_ONE_CONVERSATION'
	type.DELETE_ONE_CONVERSATION = 'DELETE_ONE_CONVERSATION'
	type.TOGGLE_CURRENT_CONVERSATION = 'TOGGLE_CURRENT_CONVERSATION'

	type.GET_TOTAL_UNREAD_COUNT = 'GET_TOTAL_UNREAD_COUNT'

    type.CLEAR_CON_MESSAGE_LIST = 'CLEAR_CON_MESSAGE_LIST'
	type.ADD_ONE_MESSAGE = 'ADD_ONE_MESSAGE'
	type.SHIFT_ONE_MESSAGE = 'SHIFT_ONE_MESSAGE'
	type.DELETE_ONE_MESSAGE = 'DELETE_ONE_MESSAGE'
    type.TOGGLE_CHECKBOX_STATUS = 'TOGGLE_CHECKBOX_STATUS'
	type.CLEAR_CHECKBOX_STATUS = 'CLEAR_CHECKBOX_STATUS'
	type.UPDATE_MESSAGE_READ_STATUS = 'UPDATE_MESSAGE_READ_STATUS'
	type.UPDATE_LISTENED_STATUS = 'UPDATE_LISTENED_STATUS'
	type.UPDATE_TEXT_CONTENT = 'UPDATE_TEXT_CONTENT'
	type.TOGGLE_TEXT_CONTEN_DISPLAY = 'TOGGLE_TEXT_CONTEN_DISPLAY'

	type.CONTEXT_MENU_OBJ = 'CONTEXT_MENU_OBJ'
	type.CONTEXT_MENU_EVENT = 'CONTEXT_MENU_EVENT'

	type.TOGGLE_MULTIPLE_STATUS = 'TOGGLE_MULTIPLE_STATUS'
export default type
